service:
  extensions: [jaeger_storage, jaeger_query, remote_sampling, healthcheckv2, expvar, zpages]
  pipelines:
    traces:
      receivers: [otlp, jaeger, zipkin]
      processors: [batch]
      exporters: [jaeger_storage_exporter]

extensions:
  jaeger_query:
    storage:
      traces: badger_storage

  jaeger_storage:
    backends:
      badger_storage:
        badger:
          keys_path: /badger/keys
          values_path: /badger/values
          metadata_path: /badger/meta
          storage_type: ""

  remote_sampling:

  healthcheckv2:

  expvar:

  zpages:

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"
  jaeger:
    protocols:
      grpc:
        endpoint: "0.0.0.0:14250"
      thrift_http:
        endpoint: "0.0.0.0:14268"
  zipkin:
    endpoint: "0.0.0.0:9411"

processors:
  batch:

exporters:
  jaeger_storage_exporter:
