server:
  port: 0
  shutdown: graceful
spring:
  profiles:
    active: dev
  application:
    name: goodskill-order
  main:
    allow-circular-references: true
  config:
    import:
      - optional:nacos:goodskill-common-connection.yml
      - optional:nacos:goodskill-common.yml
  cloud:
    nacos:
      username: nacos
      password: nacos
      server-addr: nacos:8848
    function:
      ## 绑定的消息处理函数名
      definition: seckillMongoSave
    stream:
      default-binder: rabbit
      bindings:
        seckillMongoSave-in-0:
          ##解决重复消费问题，注意：同一组下只消费一次
          group: default
          destination: seckill-order-save
  data:
    mongodb:
      auto-index-creation: true

logging:
  level:
    org:
      springframework:
        data:
          mongodb: debug

