server:
  port: 0
  shutdown: graceful
spring:
  profiles:
    active: dev
  application:
    name: goodskill-order
  main:
    allow-circular-references: true
  config:
    import:
      - optional:nacos:goodskill-common-connection.yml
      - optional:nacos:goodskill-common.yml
  cloud:
    nacos:
      username: nacos
      password: nacos
      server-addr: nacos:8848
    function:
      ## 绑定的消息处理函数名
      definition: seckillMongoSave
    stream:
      default-binder: rabbit
      bindings:
        seckillMongoSave-in-0:
          ##解决重复消费问题，注意：同一组下只消费一次
          group: default
          destination: seckill-order-save
  mongodb:
    auto-index-creation: true


logging:
  level:
    org:
      springframework:
        data:
          mongodb: debug

# 支付宝配置
alipay:
  appId: 2021000000000000
  privateKey: 私钥
  publicKey: 支付宝公钥
  gateway: openapi-sandbox.dl.alipaydev.com
  notifyUrl: http://localhost:54870/api/pay/alipay/callback
  returnUrl: http://localhost:54870/api/pay/alipay/return
