spring:
  application:
    name: goodskill-oauth2-authorization
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-stcsm.gobestsoft.cn:31714/gs_user?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: password
  sql:
    init:
      schema-locations: classpath*:users.ddl
      mode: ALWAYS
      continue-on-error: true
