create table GOODS
(
    GOODS_ID    INTEGER,
    PHOTO_URL   CHARACTER VARYING(200),
    NAME        CHARACTER VARYING(45),
    PRICE       CHARACTER VARYING(45),
    CREATE_TIME TIMESTAMP,
    INTRODUCE   CHARACTER VARYING(500)
);

create table PERMISSION
(
    PERMISSION_ID        BIGINT,
    PERMISSION_NAME      CHARACTER VARYING(64),
    CREATE_TIME          TIMESTAMP,
    UPDATE_TIME          TIMESTAMP,
    PERMISSION_MENU      CHARACTER VARYING(500),
    PARENT_PERMISSION_ID INTEGER,
    IS_DIR               CHARACTER VARYING(1),
    ORDER_NO             INTEGER
);

create table ROLE
(
    ROLE_ID     BIGINT,
    ROLE_NAME   CHARACTER VARYING(64),
    CREATE_TIME TIMESTAMP,
    UPDATE_TIME TIMESTAMP
);

create table ROLE_PERMISSION
(
    ID            BIGINT,
    PERMISSION_ID BIGINT,
    ROLE_ID       BIGINT,
    CREATE_TIME   TIMESTAMP,
    UPDATE_TIME   TIMESTAMP
);

create table SECKILL
(
    SECKILL_ID  BIGINT,
    NAME        CHARACTER VARYING(120),
    NUMBER      INTEGER,
    START_TIME  TIMESTAMP,
    END_TIME    TIMESTAMP,
    CREATE_TIME TIMESTAMP,
    GOODS_ID    INTEGER,
    PRICE       NUMERIC(10, 2),
    STATUS      CHARACTER VARYING(5),
    CREATE_USER CHARACTER VARYING(45)
);

create table SUCCESS_KILLED
(
    SECKILL_ID  BIGINT,
    USER_PHONE  CHARACTER VARYING(20),
    STATUS      TINYINT,
    CREATE_TIME TIMESTAMP,
    SERVER_IP   CHARACTER VARYING(200),
    USER_IP     CHARACTER VARYING(200),
    USER_ID     CHARACTER VARYING(45)
);

create table SUCCESS_KILLED_0
(
    SECKILL_ID  BIGINT,
    USER_PHONE  CHARACTER VARYING(20),
    STATUS      TINYINT,
    CREATE_TIME TIMESTAMP,
    SERVER_IP   CHARACTER VARYING(200),
    USER_IP     CHARACTER VARYING(200),
    USER_ID     CHARACTER VARYING(45)
);

create table SUCCESS_KILLED_1
(
    SECKILL_ID  BIGINT,
    USER_PHONE  CHARACTER VARYING(20),
    STATUS      TINYINT,
    CREATE_TIME TIMESTAMP,
    SERVER_IP   CHARACTER VARYING(200),
    USER_IP     CHARACTER VARYING(200),
    USER_ID     CHARACTER VARYING(45)
);

create table SYS_DICT
(
    ID          CHARACTER(32),
    PARENT_ID   CHARACTER(32),
    DICT_CODE   CHARACTER VARYING(255),
    DICT_KEY    CHARACTER VARYING(255),
    DICT_VALUE  CHARACTER VARYING(255),
    DESCRIPTION CHARACTER VARYING(255),
    SORT_NO     INTEGER,
    STATUS      TINYINT,
    DEL_FLAG    TINYINT,
    ROOT_FLAG   TINYINT,
    UPDATE_USER CHARACTER VARYING(32),
    UPDATE_TIME TIMESTAMP,
    CREATE_USER CHARACTER VARYING(32),
    CREATE_TIME TIMESTAMP
);

create table SYS_DICT_BIZ
(
    ID          CHARACTER(32),
    PARENT_ID   CHARACTER(32),
    DICT_CODE   CHARACTER VARYING(255),
    DICT_KEY    CHARACTER VARYING(255),
    DICT_VALUE  CHARACTER VARYING(255),
    DESCRIPTION CHARACTER VARYING(255),
    SORT_NO     INTEGER,
    STATUS      TINYINT,
    DEL_FLAG    TINYINT,
    ROOT_FLAG   TINYINT,
    SYS_CODE    CHARACTER VARYING(10),
    UPDATE_USER CHARACTER VARYING(32),
    UPDATE_TIME TIMESTAMP,
    CREATE_USER CHARACTER VARYING(32),
    CREATE_TIME TIMESTAMP
);

create table USER_AUTH_ACCOUNT
(
    ID                 BIGINT,
    USER_ID            INTEGER,
    THIRD_ACCOUNT_ID   CHARACTER VARYING(200),
    THIRD_ACCOUNT_NAME CHARACTER VARYING(100),
    SOURCE_TYPE        CHARACTER VARYING(50),
    CREATE_TIME        TIMESTAMP,
    UPDATE_TIME        TIMESTAMP
);

create table USER_ROLE
(
    ID          BIGINT,
    USER_ID     BIGINT,
    ROLE_ID     BIGINT,
    CREATE_TIME TIMESTAMP,
    UPDATE_TIME TIMESTAMP
);

create table UNDO_LOG
(
    ID            BIGINT,
    BRANCH_ID     BIGINT,
    XID           CHARACTER VARYING(100),
    CONTEXT       CHARACTER VARYING(128),
    ROLLBACK_INFO BINARY LARGE OBJECT,
    LOG_STATUS    INTEGER,
    LOG_CREATED   TIMESTAMP,
    LOG_MODIFIED  TIMESTAMP,
    EXT           CHARACTER VARYING(100)
);

create table USER_H2
(
    ID          BIGINT,
    ACCOUNT     CHARACTER VARYING(45),
    PASSWORD    CHARACTER VARYING(45),
    CREATE_TIME TIMESTAMP,
    UPDATE_TIME TIMESTAMP,
    USERNAME    CHARACTER VARYING(50),
    LOCKED      CHARACTER VARYING(1)
);



