create table GOODS
(
	GOODS_ID INTEGER  auto_increment
		primary key,
	PHOTO_URL VARCHAR(200) default 'NULL',
	NAME VARCHAR(45) default 'NULL',
	PRICE VARCHAR(45) default 'NULL',
	CREATE_TIME TIMESTAMP(26,6) default NULL,
	INTRODUCE VARCHAR(500) default 'NULL',
	PHOTO_IMAGE BLOB
);

create table PERMISSION
(
	PERMISSION_ID INTEGER not null
		primary key,
	PERMISSION_NAME VARCHAR(64) default 'NULL',
	CREATE_TIME TIMESTAMP(26,6) default NULL,
	UPDATE_TIME TIMESTAMP(26,6) default CURRENT_TIMESTAMP,
	PERMISSION_MENU VARCHAR(500) default 'NULL',
	PARENT_PERMISSION_ID INTEGER default NULL,
	IS_DIR VARCHAR(1) default 'NULL',
	ORDER_NO INTEGER default NULL
);

create table ROLE
(
	ROLE_ID INTEGER auto_increment
		primary key,
	ROLE_NAME VARCHAR(64) default 'NULL',
	CREATE_TIME TIMESTAMP(26,6) default NULL,
	UPDATE_TIME TIMESTAMP(26,6) default CURRENT_TIMESTAMP
);

create table ROLE_PERMISSION
(
	ID INTEGER not null
		primary key,
	PERMISSION_ID INTEGER,
	ROLE_ID INTEGER,
	CREATE_TIME TIMESTAMP(26,6),
	UPDATE_TIME TIMESTAMP(26,6)
);

create table SECKILL
(
	SECKILL_ID BIGINT not null
		primary key,
	NAME VARCHAR(120),
	NUMBER INTEGER,
	START_TIME TIMESTAMP(26,6) default CURRENT_TIMESTAMP,
	END_TIME TIMESTAMP(26,6) default CURRENT_TIMESTAMP,
	CREATE_TIME TIMESTAMP(26,6) default CURRENT_TIMESTAMP,
	GOODS_ID INTEGER,
	PRICE DECIMAL(10,2),
	STATUS VARCHAR(5),
	CREATE_USER VARCHAR(45)
);

create index IDX_CREATE_TIME
	on SECKILL (CREATE_TIME);

create index IDX_END_TIME
	on SECKILL (END_TIME);

create index IDX_START_TIME
	on SECKILL (START_TIME);

create table SUCCESS_KILLED
(
	SECKILL_ID BIGINT not null,
	USER_PHONE VARCHAR(20) not null,
	STATUS INTEGER default -1,
	CREATE_TIME TIMESTAMP(26,6) default CURRENT_TIMESTAMP,
	SERVER_IP VARCHAR(200),
	USER_IP VARCHAR(200),
	USER_ID VARCHAR(45),
	primary key (SECKILL_ID, USER_PHONE)
);

create table USER
(
	ID INTEGER  auto_increment
		primary key,
	ACCOUNT VARCHAR(45) not null
		unique,
	PASSWORD VARCHAR(45) default 'aa123456' not null,
	CREATE_TIME TIMESTAMP(26,6) default CURRENT_TIMESTAMP not null,
	UPDATE_TIME TIMESTAMP(26,6) default CURRENT_TIMESTAMP not null,
	USERNAME VARCHAR(50) default 'NULL',
	LOCKED VARCHAR(1) default '0'
);

create table USER_ROLE
(
	ID INTEGER not null
		primary key,
	USER_ID INTEGER,
	ROLE_ID INTEGER,
	CREATE_TIME TIMESTAMP(26,6),
	UPDATE_TIME TIMESTAMP(26,6)
);

