package org.seckill.dao;

import org.apache.ibatis.annotations.Param;
import org.seckill.entity.Seckill;
import org.seckill.entity.SeckillExample;

import java.util.Date;
import java.util.List;

public interface SeckillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbg.generated
     */
    long countByExample(SeckillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbg.generated
     */
    int deleteByExample(SeckillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long seckillId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbg.generated
     */
    int insert(Seckill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbg.generated
     */
    int insertSelective(Seckill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbg.generated
     */
    List<Seckill> selectByExample(SeckillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbg.generated
     */
    Seckill selectByPrimaryKey(Long seckillId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Seckill record, @Param("example") SeckillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Seckill record, @Param("example") SeckillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Seckill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Seckill record);

    int reduceNumber(long seckillId, Date nowTime);
}