package org.seckill.dao;

import java.util.List;
import org.seckill.entity.Seckill;
import org.seckill.entity.SeckillExample;

public interface SeckillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long seckillId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbg.generated
     */
    int insert(Seckill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbg.generated
     */
    int insertSelective(Seckill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbg.generated
     */
    List<Seckill> selectByExample(SeckillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbg.generated
     */
    Seckill selectByPrimaryKey(Long seckillId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Seckill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Seckill record);
}