package org.seckill.dao;

import org.apache.ibatis.annotations.Param;
import org.seckill.entity.SuccessKilled;

public interface SuccessKilledMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_killed
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("seckillId") Long seckillId, @Param("userPhone") String userPhone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_killed
     *
     * @mbg.generated
     */
    int insert(SuccessKilled record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_killed
     *
     * @mbg.generated
     */
    int insertSelective(SuccessKilled record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_killed
     *
     * @mbg.generated
     */
    SuccessKilled selectByPrimaryKey(@Param("seckillId") Long seckillId, @Param("userPhone") String userPhone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_killed
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SuccessKilled record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_killed
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SuccessKilled record);
}