server:
  port: 18077

spring:
  application:
    name: goodskill-ai
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
  cloud:
    nacos:
      username: nacos
      password: nacos
      server-addr: nacos:8848
  config:
    import:
      - optional:nacos:goodskill-common-connection.yml
      - optional:nacos:goodskill-common.yml
